
version: '2'
services:
  zookeeper:
    image: zookeeper:3.5.9
    ports:
      - "2181:2181"
    networks:
      - kafkanet
  kafka:
    image: includeno/kafka:1.0.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - kafkanet
    depends_on:
      - zookeeper
networks:
  kafkanet:
    driver: bridge